name: 'Setup III Engine'
description: 'Download, cache, and start the III Engine server for integration tests'

inputs:
  engine-repo:
    description: 'GitHub repository containing the III Engine releases (e.g., owner/repo)'
    required: false
    default: ''
  engine-version:
    description: 'Engine version to download (default: latest)'
    required: false
    default: 'latest'
  config-path:
    description: 'Path to engine config YAML file'
    required: false
    default: '.github/engine-config/test-config.yml'
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  engine-available:
    description: 'Whether the engine is available and running'
    value: ${{ steps.final.outputs.engine-available }}

runs:
  using: composite
  steps:
    - name: Resolve engine repository and version
      id: resolve
      shell: bash
      run: |
        ENGINE_REPO="${INPUT_ENGINE_REPO:-${{ github.repository_owner }}/iii}"
        ENGINE_VERSION="${INPUT_ENGINE_VERSION:-latest}"
        PLATFORM="x86_64-unknown-linux-gnu"

        echo "engine_repo=$ENGINE_REPO" >> $GITHUB_OUTPUT
        echo "engine_version=$ENGINE_VERSION" >> $GITHUB_OUTPUT
        echo "platform=$PLATFORM" >> $GITHUB_OUTPUT

        if [ "$ENGINE_VERSION" = "latest" ]; then
          if ! RELEASE_TAG=$(gh api repos/$ENGINE_REPO/releases/latest --jq .tag_name 2>/dev/null); then
            echo "Could not find latest release in $ENGINE_REPO"
            echo "release_tag=" >> $GITHUB_OUTPUT
            echo "engine_available=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [ -z "$RELEASE_TAG" ] || [ "$RELEASE_TAG" = "null" ] || [[ "$RELEASE_TAG" == *"message"* ]] || [[ "$RELEASE_TAG" == *"Not Found"* ]]; then
            echo "Invalid release tag returned: $RELEASE_TAG"
            echo "Could not find latest release in $ENGINE_REPO"
            echo "release_tag=" >> $GITHUB_OUTPUT
            echo "engine_available=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Found latest release: $RELEASE_TAG"
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
        else
          echo "Using specified version: $ENGINE_VERSION"
          echo "release_tag=$ENGINE_VERSION" >> $GITHUB_OUTPUT
        fi
      env:
        INPUT_ENGINE_REPO: ${{ inputs.engine-repo }}
        INPUT_ENGINE_VERSION: ${{ inputs.engine-version }}
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Cache engine binary
      id: cache
      uses: actions/cache@v4
      with:
        path: /tmp/iii-engine-cache
        key: iii-engine-${{ steps.resolve.outputs.platform }}-${{ steps.resolve.outputs.release_tag }}
        restore-keys: |
          iii-engine-${{ steps.resolve.outputs.platform }}-

    - name: Download and setup engine
      id: setup
      if: steps.resolve.outputs.engine_available != 'false' && steps.resolve.outputs.release_tag != ''
      shell: bash
      run: |
        ENGINE_REPO="${{ steps.resolve.outputs.engine_repo }}"
        RELEASE_TAG="${{ steps.resolve.outputs.release_tag }}"
        PLATFORM="${{ steps.resolve.outputs.platform }}"

        mkdir -p /tmp/iii-engine
        cd /tmp/iii-engine

        if [ -f "/tmp/iii-engine-cache/iii" ]; then
          echo "Using cached engine binary"
          cp /tmp/iii-engine-cache/iii ./iii
        else
          echo "Downloading engine binary..."
          if [[ "$PLATFORM" == *"windows"* ]]; then
            ARCHIVE="iii-${PLATFORM}.zip"
            gh release download "$RELEASE_TAG" -R "$ENGINE_REPO" -p "$ARCHIVE" || {
              echo "Failed to download $ARCHIVE"
              echo "engine_available=false" >> $GITHUB_OUTPUT
              exit 0
            }
            unzip -q "$ARCHIVE"
          else
            ARCHIVE="iii-${PLATFORM}.tar.gz"
            gh release download "$RELEASE_TAG" -R "$ENGINE_REPO" -p "$ARCHIVE" || {
              echo "Failed to download $ARCHIVE"
              echo "engine_available=false" >> $GITHUB_OUTPUT
              exit 0
            }
            tar -xzf "$ARCHIVE"
          fi

          if [ ! -f "iii" ]; then
            echo "Engine binary 'iii' not found in archive"
            echo "engine_available=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          mkdir -p /tmp/iii-engine-cache
          cp iii /tmp/iii-engine-cache/iii
        fi

        chmod +x iii
        echo "$(pwd)" >> $GITHUB_PATH
        echo "engine_available=true" >> $GITHUB_OUTPUT
        echo "Engine binary ready at $(pwd)/iii"
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Start engine server
      id: start
      if: steps.setup.outputs.engine_available == 'true'
      shell: bash
      run: |
        mkdir -p /tmp/iii-engine-data
        cd /tmp/iii-engine-data

        CONFIG_PATH="${{ github.workspace }}/${{ inputs.config-path }}"
        if [ -f "$CONFIG_PATH" ]; then
          cp "$CONFIG_PATH" ./config.yml
          echo "Using config from $CONFIG_PATH"
        else
          echo "Config file not found at $CONFIG_PATH, using default config"
        fi

        echo "Starting III Engine..."
        /tmp/iii-engine/iii --config config.yml > /tmp/iii-engine.log 2>&1 &
        ENGINE_PID=$!
        echo $ENGINE_PID > /tmp/iii-engine.pid
        
        sleep 3
        
        if ps -p $ENGINE_PID > /dev/null 2>&1; then
          echo "III Engine started with PID $ENGINE_PID"
        else
          echo "Failed to start III Engine. Last 20 lines of log:"
          tail -n 20 /tmp/iii-engine.log || echo "No log file found"
          exit 1
        fi

    - name: Wait for engine health check
      id: healthcheck
      if: steps.setup.outputs.engine_available == 'true'
      shell: bash
      run: |
        echo "Waiting for engine to be ready at http://localhost:3111"
        for i in {1..30}; do
          if curl -s http://localhost:3111/ >/dev/null 2>&1; then
            echo "Engine is ready!"
            echo "engine_available=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Waiting for engine... ($i/30)"
          sleep 2
        done
        echo "Engine did not become ready in time"
        echo "Checking if process is still running..."
        if [ -f /tmp/iii-engine.pid ]; then
          PID=$(cat /tmp/iii-engine.pid)
          if ps -p $PID > /dev/null 2>&1; then
            echo "Engine process is running but not responding"
          else
            echo "Engine process has died"
          fi
        fi
        echo "engine_available=false" >> $GITHUB_OUTPUT
        exit 1

    - name: Set final output
      id: final
      if: always()
      shell: bash
      run: |
        RESOLVE_OUTPUT="${{ steps.resolve.outputs.engine_available }}"
        SETUP_OUTPUT="${{ steps.setup.outputs.engine_available }}"
        HEALTHCHECK_OUTPUT="${{ steps.healthcheck.outputs.engine_available }}"

        if [ "$RESOLVE_OUTPUT" = "false" ] || [ "$SETUP_OUTPUT" = "false" ] || [ "$HEALTHCHECK_OUTPUT" = "false" ]; then
          echo "engine_available=false" >> $GITHUB_OUTPUT
        elif [ "$HEALTHCHECK_OUTPUT" = "true" ]; then
          echo "engine_available=true" >> $GITHUB_OUTPUT
        else
          echo "engine_available=false" >> $GITHUB_OUTPUT
        fi
